### PR TITLE
[DNM][V5] Proposal for FastAdapter Engine

### PR DESCRIPTION
**Pull request by mikepenz**
- Allow the FastAdapter to depend on different core implementations 
- This was initial created for the PagedListAdapter 
  - PagedListAdapter in the end was implement a lot more simple

### CODE REVIEW

**Comment by mikepenz** [comment]
Thinking more about it, it seems like total overkill. closing it for that matter

**Comment by bejibx** [comment]
Personally I was waiting for this feature so much. We extensively using `MvpItem`'s inside our adapters. The problem is we have to track removal of such items from adapter to properly clean up their resources. So we have to create our own subclass `MvpFastAdapter` and use it everywhere. The problem is new developers don't always know about this and sometimes they are using regular `FastAdapter` instead of our own subclass, which sometimes leads to pretty unpleasant bugs. 

I was hoping after this PR we could just internally switch `FastAdapter` implementation and stop worry about this kind of problems.

Oh, and also we have to disable stable Ids for for every `FastAdapter` instance we create because it messes up animations in some cases. Well, sometimes people forget this rule too.

**Comment by mikepenz** [comment]
@bejibx perhaps you can describe a bit more of your usecase, as it seems your requirements should be possible to get implemented easier than with overwriting the `FastAdapter`.

**Comment by bejibx** [comment]
Well, our adapter looks like this:

```java
public class MvpFastAdapter<Item extends IItem<?>> extends FastAdapter<Item> {

    @Override
    public void notifyAdapterItemInserted(final int position) {
        super.notifyAdapterItemInserted(position);
        final Item item = getItem(position);
        if (item instanceof MvpItem) {
            ((MvpItem) item).onAddedToAdapter();
        }
    }

    @Override
    public void notifyAdapterItemRemoved(final int position) {
        super.notifyAdapterItemRemoved(position);
        final Item item = getItem(position);
        if (item instanceof MvpItem) {
            ((MvpItem) item).onRemovedFromAdapter();
        }
    }

    // Some other methods

}
```

`MvpItem` can do some initialization when `onAddedToAdapter` is called and clean resources during `onRemovedFromAdapter` call.

Ideally instead of overriding `FastAdapter` we should use our own `IItemList` implementation for every `IItemAdapter` we create because it gives us better control over when items are removed from or added to the list, but there is no easy way in library to switch default implementation for `IItemList`.

So I like this proposal a lot - it creates a possibility to completely switch or slightly tune internal `FastAdapter` implementation in your project to better adapt it to some of your inner mechanics. Something like `io.reactivex.plugins.RxJavaPlugins`.

**Comment by mikepenz** [comment]
@bejibx 

I don't think it is very good to actually have the on added or removed from adapter methods like this. as those won't actually happen at the time an element is added or removed, and may even result in bugs. 

If the element is added to the adapter it will do so via `bindView`
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/IItem.kt#L36

And if an element is removed from the adapter it will do so via `unbindView`
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/IItem.kt#L39

those methods will be in line with the lifecycle and with the actual requirements of the adapter. as unbind will only happen when the item is really no longer bound, in your case your item may still get rendered even though you already called `onRemovedFromAdapter`

It seems to me this binds more logic to the adapter than it should know about and you actually have 2 options:

- if you use the item directly:
prepare the items and do their init before you add them to the adapter. and do the teardown after you removed them from the adapter (after)

- if you split apart model and item:
in this case I solely would suggest you depend on bind and unbind mechanisms as they are the safest approaches.

**Comment by bejibx** [comment]
Well, `bindView` will also be called when item is just scrolled out of view, which is not what we want.

**Pull request closed without merging**
