### PR TITLE
Working `withSurfaceThreshold` for `SimpleSwipeDrawerCallback`

### PR DESCRIPTION
**Pull request by RobbWatershed**

### CODE REVIEW

**Review by mikepenz — APPROVED** [review]

**Comment by RobbWatershed** [comment]
Just added something else I just noticed today - if the click event is consumed, that info has to be communicated to the handler.

**Comment by RobbWatershed** [comment]
Definitely done with my testing. Would be fantastic if you could release that during the week 👍

**Review by mikepenz — APPROVED** [review]

**Comment by mikepenz** [comment]
@RobbWatershed https://github.com/mikepenz/FastAdapter/releases/tag/v5.3.1 here you go :)

**Comment by RobbWatershed** [comment]
Thanks a lot @mikepenz !!

**Pull request merged**
