### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by barodapride**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
https://github.com/mikepenz/FastAdapter/pull/763#issuecomment-476009645

**Comment by barodapride** [comment]
I still don't understand what to do. Does the readme need updating?

**Comment by mikepenz** [comment]
I don't know but the item is in our sample app and works perfectly:

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java#L120

**Comment by barodapride** [comment]
I guess I must have the wrong version of StringHolder. I thought I made sure I had the latest materialdrawer. I'm pretty confused about the dependency versions that I really need with the version of this fastadapter library that I'm using. Will check tonight

**Pull request closed without merging**
