### PR TITLE
Jekyll configs for automatic github pages

### PR DESCRIPTION
**Pull request by AllanWang**
In light of #474 , if you've previously auto generated the pages and would like to keep it in sync with the Read me for future builds, you may consider using the following. Especially since you won't want to invest more time in customizing the gh page, it may make sense to do the following since users might choose to read the website.

### CODE REVIEW

**Comment by mikepenz** [comment]
@AllanWang I never used this before. Anything else required to set this up?

**Comment by AllanWang** [comment]
@mikepenz Nope. I use it for [KAU](https://allanwang.github.io/KAU/) and it basically converts your md files to html files (including the changelog as you can see). Just change your page to build from master and it should all update automatically. It also works for subdirectories if you choose to put read me files in your submodules as well.

**Comment by AllanWang** [comment]
After you switch your page to load from master you might need to push a new commit to master for it to build

**Comment by mikepenz** [comment]
yeah. this will happen as soon as I do a new release, right now I'll temporarily keep the README alone :D

**Pull request merged**
