### PR TITLE
Swipe remove with in-place undo and "leave-behind" from enhancement issue #43

### PR DESCRIPTION
**Pull request by mattiasbe**
Swipe remove with in-place undo and "leave-behind" from enhancement issue #43 
See discussion there.
This adds swipe in two directions to the sample app in a separate activity, while preserving ability to drag (optional). Different swipe directions can be specified with optionally different actions along with icons and background color. Undo of said actions is also possible and included in the example. The undo option is also in place and times out of 3s in the example. A future update could let that stay until scrolled like in the gmail app.

Example app:
swipe_2

### CODE REVIEW

**Comment by mikepenz** [comment]
@mattiasbe oh i think i can't merge your pull request. Seems like you merged the `master` into the `develop` :/ You may could cherry-pick all your changes into a clean branch, branched from the develop. 

As you see above your PR also contains all my releases etc. :/

**Comment by mattiasbe** [comment]
Ouch, sorry about that, teaches you not to do things a 2.30am. I tried the menu i Android Studio named "Rebase my Github fork" and didn't pay attention it seems. Unfortunately I did this before the last commit so not trivial to reset it seems according to my git reflog. I'll try and fix it or cherry pick in a new branch as you say.

**Comment by mikepenz** [comment]
@mattiasbe no problem. Still thank you so much!

**Comment by Rainer-Lang** [comment]
@mattiasbe Such nights are great :-D

**Comment by mattiasbe** [comment]
Closing as new clean PR created.  That menu option seems really dangerous, it assumes master it seems to me and doesn't ask about much. Maybe one needs to have created the PR from inside intellij/AS as well etc.

**Comment by mikepenz** [comment]
@mattiasbe I use SourceTree, it features a GitFlow button (or at least previous versions did, the latest version removed it --> shortcut **CMD + ALT + F** is a good workaround here :D)

**Pull request closed without merging**
