### PR TITLE
[WIP] FastAdapter v4

### PR DESCRIPTION
**Pull request by FabianTerhorst**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
TODO

- how to handle select extension? Add kotlin extension function to SelectExtension to make it easier to attach to fastAdapter and get from fastAdapter.
- add migration.md

**Comment by FabianTerhorst** [comment]
TODO: 
- maybe allow adding items to an model adapter without an attached fast adapter and fix item positions on addAdapter

**Comment by FabianTerhorst** [comment]
TODO:

- move select, deselect handling from expandable extension to select extension

**Comment by mikepenz** [comment]
This can be tested by using its latest release v4.0.0-beta1

**Comment by mikepenz** [comment]
The final release of v4 is getting closer and closer :D 

To everybody interested. Please give it a try and give some final thoughts. 

```
implementation 'com.mikepenz:fastadapter:4.0.0-rc01'
```

**Pull request merged**
