### PR TITLE
Fix broken swipe distance when item width < recyclerView's width

### PR DESCRIPTION
**Pull request by RobbWatershed**
This time I'm fixing a broken swipe animation that happens when using a grid layout instead of a linear layout. The details are in the comment I left in the code.

Thanks~

PS : Sorry for the fragmented PR's, but I'm discovering issues step by step, as I'm extending my use of FastAdapter to create new features.

### CODE REVIEW

**Comment by mikepenz** [comment]
This still seems to have some strange behavior
[device-2020-11-26-132303.mp4.zip](https://github.com/mikepenz/FastAdapter/files/5602936/device-2020-11-26-132303.mp4.zip)

**Comment by RobbWatershed** [comment]
That can be explained :

- **Immobile items** : You might not remember it, but `SwipeListActivity` and `SwipeDrawerListActivity` showcase the ability to set the "swipable" property individually. Hence line 92 of `SwipeDrawerListActivity` that says
```kotlin
swipeableItem.withIsSwipeable(i % 5 != 0)
```
that's why item 16 is blocked (16 being the 15th item in a 0-indexed list)

- **Weird button display when swiping right** : That's due to the fact that the layout constraints defined in `swipeable_drawer_item.xml` haven't been designed with half the screen width in mind :
  - On the left side, the Archive and Share buttons have each a fixed width of 80dp
  - On the right side, the Delete button has a fixed width of 80dp

As a consequence, when the item only takes up half the screen width, the two buttons on the left and the button on the right _overlap_, which creates what you've seen. This is a layout issue that has nothing to do with the fix suggested in this PR.

I think the fix will be easier to check if you set `.withSwipeRight(80)` on line 112 of `SwipeDrawerListActivity`, which should allow to swipe right to the width of the Archive button only 😄

**Comment by mikepenz** [comment]
Thanks for mentioning these things again, but the main problem I actually see is, that I can't drag back to dismiss. it seems to not take the action. It works though with full width beautifully. 

Can you also please try that one if it works for you fully?

**Comment by RobbWatershed** [comment]
You're right, when using a two-column grid view, it takes multiple swipes to dismiss the view. I'm gonna investigate this.

**Comment by RobbWatershed** [comment]
That's done ! There were two other issues I solved in today's batch.

PS : Not sure about how to solve the merge conflict myself...

**Comment by mikepenz** [comment]
Looks good :D thank you so much for the fixes

**Comment by RobbWatershed** [comment]
> Looks good :D thank you so much for the fixes
Neat !!

I'm gonna do some research on the differ and the loading system, as I'm facing crashes on certain devices (~4% of my users). Stay tuned for more discussions / PRs...

**Comment by mikepenz** [comment]
@RobbWatershed thanks a ton.

**Pull request merged**
