### PR TITLE
SubItemUtil + DragSelection

### PR DESCRIPTION
**Pull request by MFlisar**
* commented out some logs
* added an id collection based delete function
* added an id based notifier function
* changed the RangeSelectorHelper `selectRange` functions visibility (so that I can use it in other places as well, i.e. in my google like swipe selector)

### CODE REVIEW

**Comment by mikepenz** [comment]
@MFlisar sorry for not yet merging this. Is this still ready?

**Comment by MFlisar** [comment]
Sure, I anyways only touched the utility class...

And the Drag Selection is anyways an external library as it works without your adapter as well of course. It's up to you though if you want to add my demo with it as well...

**Comment by MFlisar** [comment]
The last 2 commits are only one single change: `fastAdapter.deselect()` will check, if an item is checked and only unchecks them if they are checked. Problem with the old solution was, that for example the `ActionModeHelper` may call `deselect()` if you finish the `ActionMode` and this will iterate over all items and then notify a selection listener (if there is one) and this may be a lot of unnecessary (and wrong) work

**Comment by mikepenz** [comment]
@MFlisar thank you

**Pull request merged**
