### PR TITLE
 Unit test for #955 

### PR DESCRIPTION
**Pull request by RobbWatershed**

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you. I'll hope to be able to have a look at this tomorrow

**Comment by mikepenz** [comment]
@RobbWatershed so I looked into the test, and it looks to me that this test shows that the library works as expected. 

The adapter gets updated with new item instances which are no longer selected. They share the same identifier but are new items (new references). 

The `FastAdapter` can't make the assumption to keep selections for those items, as they were provided unselected. Which is seen as the decision made by the dev to have them no longer being in a selected state. 

What you can do instead though for example. remember the selections as they were before modifying the adapter, and re-applying those. 

```
        Bundle bundle = new Bundle();
        selectExtension.saveInstanceState(bundle, "test");

        // Refresh the list with the same items
        FastAdapterDiffUtil.INSTANCE.set(itemAdapter, TestDataGenerator.genTestItemList(100));

        selectExtension.withSavedInstanceState(bundle, "test");
```


This surely gets a bit more complicated if you use async differ or such. 

------

I wonder though. If you use a `ModelAdapter` instead of an `ItemAdapter` and have model and item be different. theoretically the differ should be able to keep the same `Item` if the `Model` stays the same. (if data changes, it would be a different story though)

**Comment by RobbWatershed** [comment]
Thanks for the explanation.

That lead me to take a different approach and use `selectExtension.setSelectWithItemUpdate(true)`, which behaves just like I need with a few minors adjustments !

**Comment by mikepenz** [comment]
@RobbWatershed that's great :) thank you so much for the test case. and for the description :)

**Pull request closed without merging**
