### PR TITLE
Fix drag & drop issues in SimpleDragCallback

### PR DESCRIPTION
**Pull request by cketti**
This fixes a couple of issues in `SimpleDragCallback` (see individual commits) and adds a new activity showing off how to reorder (parts of) a list.

https://user-images.githubusercontent.com/218061/111382299-1979b880-86a7-11eb-97fc-7f5886c2f13d.mp4

### CODE REVIEW

**Comment by mikepenz** [comment]
That's amazing. thank you so much for the PR. will look into it asap

**Comment by mikepenz** [comment]
I believe danger is failing because of this coming from a fork and it ain't have the right permission to run :/ will look into that seperately

**Review by mikepenz — APPROVED** [review]

**Comment by mikepenz** [comment]
Once again. thank you so much for the great PR. Released it as v5.4.0-b01 in case it's blocking the PR you have open on k-9 mail

**Comment by cketti** [comment]
> Once again. thank you so much for the great PR. Released it as v5.4.0-b01 in case it's blocking the PR you have open on k-9 mail

Awesome. Thanks :heart:

**Pull request merged**
