### PR TITLE
Drawer swipe [#905]

### PR DESCRIPTION
**Pull request by RobbWatershed**
Implementation for drawer swipe, as described in #905 

**Usage**

* Very similar to `SimpleSwipeCallback`
* Give max drawer width (in `dp`) to `withSwipeLeft` and `withSwipeRight` during construction
* Corresponding `ViewHolder` must implement `IDrawerSwipeableViewHolder` to indicate which `View` will slide with the swipe gesture. The views below may display clickable buttons
* Use `SimpleSwipeDrawerDragCallback` to enable drag + swipe

**Important / For your consideration**

When the sliding view has been swiped, the buttons located below are visible on screen, however, when tapping on them, the default Android touch even dispatch mechanism doesn't transmit the tap event to the buttons : any click on the exposed surface just swipes the item back to where it came.

To enable the touch events to actually reach the buttons below, I had to implement a small hack that uses `OnTouchListener` (see `SimpleSwipeDrawerCallback.RecyclerTouchTransmitter`).

It works well but has a price : **any `OnTouchListener` the user would have previously set on the `RecyclerView` will be overriden by `FastAdapter`'s own `OnTouchListener`.**

Is that acceptable to you ?

***

drawerSwipe

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you so much for the PR I'll have a look and will try to find a good answer for the touch listener situation :)

**Comment by mikepenz** [comment]
I have had a look on your implementation and tried a few different things in regards to the on touch listener, but I couldn't find anything alternative for now. I suppose it is fine as it is a very special usecase, and if a user needs something even more complex than the `simple` prepared functionalities may not be enough regardless :) 

Sadly it seems we can't really animate the collapsing of the item. which would make it's UX even more amazing. 

Thank you so much for your PR and work :)

**Comment by mikepenz** [comment]
Thanks for your contributions. They are added and released in v5.2.0 :) 

Also I have added a mention to you in the README as a thanks to your contributions

**Comment by RobbWatershed** [comment]
Awesome 😁 Thank you for your trust and enthusiastic responsiveness Mike !

**Pull request merged**
