### PR TITLE
[DO NOT MERGE] Add test case for 491

### PR DESCRIPTION
**Pull request by FabianTerhorst**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
@sosite do you know an way to reproduce #491?

**Comment by sosite** [comment]
@FabianTerhorst I guess you can't reproduce it by simple create 2 item adapters as I describe in #491 and remove item from the 2nd one?

**Comment by FabianTerhorst** [comment]
Not inside Robolectric it looks like.

**Comment by mikepenz** [comment]
@sosite but the issue is still occurring for you?

**Pull request closed without merging**
